// Mocks generated by Mockito 5.4.6 from annotations
// in klimatrack_app/test/usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:klimatrack_app/core/constants/api_format.dart' as _i6;
import 'package:klimatrack_app/data/repositories/openweather_repository.dart'
    as _i4;
import 'package:klimatrack_app/domain/entities/weather.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeather_1 extends _i1.SmartFake implements _i3.Weather {
  _FakeWeather_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OpenWeatherRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenWeatherRepositoryImpl extends _i1.Mock
    implements _i4.OpenWeatherRepositoryImpl {
  MockOpenWeatherRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i5.Future<_i3.Weather> getWeatherByCity(
    String? city,
    _i6.ApiFormat? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherByCity,
          [
            city,
            format,
          ],
        ),
        returnValue: _i5.Future<_i3.Weather>.value(_FakeWeather_1(
          this,
          Invocation.method(
            #getWeatherByCity,
            [
              city,
              format,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Weather>);

  @override
  _i5.Future<_i3.Weather> getWeatherByLocation(
    double? latitude,
    double? longitude,
    _i6.ApiFormat? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherByLocation,
          [
            latitude,
            longitude,
            format,
          ],
        ),
        returnValue: _i5.Future<_i3.Weather>.value(_FakeWeather_1(
          this,
          Invocation.method(
            #getWeatherByLocation,
            [
              latitude,
              longitude,
              format,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Weather>);
}
