// Mocks generated by Mockito 5.4.6 from annotations
// in klimatrack_app/test/features/homepage/presentation/bloc/weather_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:klimatrack_app/domain/core/result.dart' as _i7;
import 'package:klimatrack_app/domain/entities/weather.dart' as _i8;
import 'package:klimatrack_app/domain/repositories/location_repository.dart'
    as _i3;
import 'package:klimatrack_app/domain/repositories/openweather_repository.dart'
    as _i2;
import 'package:klimatrack_app/domain/usecases/get_current_location_weather.dart'
    as _i12;
import 'package:klimatrack_app/domain/usecases/get_weather_by_city.dart' as _i5;
import 'package:klimatrack_app/domain/usecases/get_weather_by_location.dart'
    as _i4;
import 'package:klimatrack_app/domain/usecases/params/get_current_location_weather_params.dart'
    as _i13;
import 'package:klimatrack_app/domain/usecases/params/get_weather_by_city_params.dart'
    as _i9;
import 'package:klimatrack_app/domain/usecases/params/get_weather_by_location_params.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOpenWeatherRepository_0 extends _i1.SmartFake
    implements _i2.OpenWeatherRepository {
  _FakeOpenWeatherRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationRepository_1 extends _i1.SmartFake
    implements _i3.LocationRepository {
  _FakeLocationRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWeatherByLocationUseCase_2 extends _i1.SmartFake
    implements _i4.GetWeatherByLocationUseCase {
  _FakeGetWeatherByLocationUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetWeatherByCityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeatherByCityUseCase extends _i1.Mock
    implements _i5.GetWeatherByCityUseCase {
  MockGetWeatherByCityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OpenWeatherRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOpenWeatherRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.OpenWeatherRepository);

  @override
  _i6.Future<_i7.Result<_i8.Weather>> call(
          _i9.GetWeatherByCityParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i7.Result<_i8.Weather>>.value(
            _i10.dummyValue<_i7.Result<_i8.Weather>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i7.Result<_i8.Weather>>);
}

/// A class which mocks [GetWeatherByLocationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeatherByLocationUseCase extends _i1.Mock
    implements _i4.GetWeatherByLocationUseCase {
  MockGetWeatherByLocationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OpenWeatherRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOpenWeatherRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.OpenWeatherRepository);

  @override
  _i6.Future<_i7.Result<_i8.Weather>> call(
          _i11.GetWeatherByLocationParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i7.Result<_i8.Weather>>.value(
            _i10.dummyValue<_i7.Result<_i8.Weather>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i7.Result<_i8.Weather>>);
}

/// A class which mocks [GetCurrentLocationWeatherUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentLocationWeatherUseCase extends _i1.Mock
    implements _i12.GetCurrentLocationWeatherUseCase {
  MockGetCurrentLocationWeatherUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LocationRepository get locationRepository => (super.noSuchMethod(
        Invocation.getter(#locationRepository),
        returnValue: _FakeLocationRepository_1(
          this,
          Invocation.getter(#locationRepository),
        ),
      ) as _i3.LocationRepository);

  @override
  _i4.GetWeatherByLocationUseCase get getWeatherByLocation =>
      (super.noSuchMethod(
        Invocation.getter(#getWeatherByLocation),
        returnValue: _FakeGetWeatherByLocationUseCase_2(
          this,
          Invocation.getter(#getWeatherByLocation),
        ),
      ) as _i4.GetWeatherByLocationUseCase);

  @override
  _i6.Future<_i7.Result<_i8.Weather>> call(
          _i13.GetCurrentLocationWeatherParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i7.Result<_i8.Weather>>.value(
            _i10.dummyValue<_i7.Result<_i8.Weather>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i7.Result<_i8.Weather>>);
}
