// Mocks generated by Mockito 5.4.6 from annotations
// in klimatrack_app/test/features/homepage/presentation/bloc/weather_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:geolocator/geolocator.dart' as _i9;
import 'package:klimatrack_app/core/constants/api_format.dart' as _i6;
import 'package:klimatrack_app/core/services/location_service.dart' as _i8;
import 'package:klimatrack_app/domain/entities/weather.dart' as _i3;
import 'package:klimatrack_app/domain/repositories/openweather_repository.dart'
    as _i2;
import 'package:klimatrack_app/domain/usecases/get_weather_by_city.dart' as _i4;
import 'package:klimatrack_app/domain/usecases/get_weather_by_location.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOpenWeatherRepository_0 extends _i1.SmartFake
    implements _i2.OpenWeatherRepository {
  _FakeOpenWeatherRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeather_1 extends _i1.SmartFake implements _i3.Weather {
  _FakeWeather_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetWeatherByCityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeatherByCityUseCase extends _i1.Mock
    implements _i4.GetWeatherByCityUseCase {
  MockGetWeatherByCityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OpenWeatherRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOpenWeatherRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.OpenWeatherRepository);

  @override
  _i5.Future<_i3.Weather> call(
    String? city,
    _i6.ApiFormat? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            city,
            format,
          ],
        ),
        returnValue: _i5.Future<_i3.Weather>.value(_FakeWeather_1(
          this,
          Invocation.method(
            #call,
            [
              city,
              format,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Weather>);
}

/// A class which mocks [GetWeatherByLocationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeatherByLocationUseCase extends _i1.Mock
    implements _i7.GetWeatherByLocationUseCase {
  MockGetWeatherByLocationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OpenWeatherRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOpenWeatherRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.OpenWeatherRepository);

  @override
  _i5.Future<_i3.Weather> call(
    double? latitude,
    double? longitude,
    _i6.ApiFormat? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            latitude,
            longitude,
            format,
          ],
        ),
        returnValue: _i5.Future<_i3.Weather>.value(_FakeWeather_1(
          this,
          Invocation.method(
            #call,
            [
              latitude,
              longitude,
              format,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Weather>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i8.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i9.Position?> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i5.Future<_i9.Position?>.value(),
      ) as _i5.Future<_i9.Position?>);

  @override
  _i5.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i9.Position?> getLastKnownLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLastKnownLocation,
          [],
        ),
        returnValue: _i5.Future<_i9.Position?>.value(),
      ) as _i5.Future<_i9.Position?>);
}
