// Mocks generated by Mockito 5.4.6 from annotations
// in klimatrack_app/test/usecases/get_current_location_weather_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:klimatrack_app/domain/entities/geo_position.dart' as _i5;
import 'package:klimatrack_app/domain/entities/weather.dart' as _i2;
import 'package:klimatrack_app/domain/repositories/location_repository.dart'
    as _i3;
import 'package:klimatrack_app/domain/repositories/openweather_repository.dart'
    as _i6;
import 'package:klimatrack_app/domain/value_objects/api_format.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeather_0 extends _i1.SmartFake implements _i2.Weather {
  _FakeWeather_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i5.GeoPosition?> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i4.Future<_i5.GeoPosition?>.value(),
      ) as _i4.Future<_i5.GeoPosition?>);
}

/// A class which mocks [OpenWeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenWeatherRepository extends _i1.Mock
    implements _i6.OpenWeatherRepository {
  MockOpenWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Weather> getWeatherByCity(
    String? city,
    _i7.ApiFormat? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherByCity,
          [
            city,
            format,
          ],
        ),
        returnValue: _i4.Future<_i2.Weather>.value(_FakeWeather_0(
          this,
          Invocation.method(
            #getWeatherByCity,
            [
              city,
              format,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Weather>);

  @override
  _i4.Future<_i2.Weather> getWeatherByLocation(
    double? latitude,
    double? longitude,
    _i7.ApiFormat? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherByLocation,
          [
            latitude,
            longitude,
            format,
          ],
        ),
        returnValue: _i4.Future<_i2.Weather>.value(_FakeWeather_0(
          this,
          Invocation.method(
            #getWeatherByLocation,
            [
              latitude,
              longitude,
              format,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Weather>);
}
